version: '3'

services:
    webservice:
        build: ./
        image: server:latest
        ports:
        -   8080:8080
        depends_on:
            -   database
    database:
        image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: database
        restart: always
        tty: true
        ports:
        -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: dfe4da18
            MYSQL_DATABASE: unyleya
            MYSQL_USER: giovane
            MYSQL_PASSWORD: giovane
        volumes:
            - ./database:/docker-entrypoint-initdb.d/
